---
title: "Random Math Problems"
author: "Sharon Hui"
date: "10/12/2024"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Integrate by Parts

### Practice Problem 1.1

$$\int \ln(x^2-x+2)dx$$

Let $u = \ln(x^2-x+2) \leftrightarrow du=\frac{2x-1}{x^2-x+2}$ and $dv = dx \leftrightarrow v=x$

$$=x\ln(x^2-x+2) -\int \frac{(2x-1)x}{x^2-x+2}dx =x\ln(x^2-x+2) -\int \frac{2x^2-x}{x^2-x+2}dx$$

Long division: $\frac{2x^2-x}{x^2-x+2} = \frac{x-4}{x^2-x+2} + 2$

$$\int \frac{2x^2-x}{x^2-x+2}dx = \int \left[\frac{x-4}{x^2-x+2} + 2 \right]dx = 2x +c_1+\int \frac{x-4}{x^2-x+2} dx=2x +c_1+\int \frac{\frac{1}{2}(2x-1)-\frac{7}{2}}{x^2-x+2} dx$$

$$=2x +c_1+ \frac{1}{2}\int \frac{2x-1}{x^2-x+2} - \int\frac{\frac{7}{2}}{x^2-x+2} dx=2x+ \frac{1}{2} \ln({x^2-x+2}) +c_2- \frac{7}{2}\int \frac{1}{\left(x-\frac{1}{2}\right)^2 + \frac{7}{4}}dx$$

$$=2x+ \frac{1}{2} \ln({x^2-x+2}) +c_2- \frac{7}{2}\int \frac{1}{ \frac{7}{4} \left[\left(\frac{\sqrt{4}}{\sqrt{7}}\left(x-\frac{1}{2}\right)\right)^2 + 1\right]}dx$$

Let $u=\sqrt{\frac{4}{7}}\left(x-\frac{1}{2}\right) \leftrightarrow du=\sqrt{\frac{4}{7}}dx$

$$=2x+ \frac{1}{2} \ln({x^2-x+2}) +c_2 - \frac{7}{2} \frac{4}{7}\sqrt{\frac{7}{4}}\int \frac{1}{u^2 + 1}du = 2x+ \frac{1}{2} \ln({x^2-x+2}) +c_2 - 2 \sqrt{\frac{7}{4}} \text{arctan}\left( \sqrt{\frac{4}{7}}\left(x-\frac{1}{2}\right)  \right)$$

So, 



$$\int \ln(x^2-x+2)dx= x\ln(x^2-x+2)  -2x- \frac{1}{2} \ln({x^2-x+2}) + \sqrt{7}\text{arctan}\left( \sqrt{\frac{4}{7}}\left(x-\frac{1}{2}\right)  \right) + C$$
\newpage



## Exact length of the curve

Given $f(x)$ and $a \leq x \leq b$, the exact length of the curve is given by 
$$L = \int_{a}^{b} \sqrt{1+ (f'(x))^2}dx$$

### Practice Problem 2.1

Find the exact length of the curve:

$x = e^y + \frac{1}{4} e^{-y}, \hspace{.5 cm} 0 \leq y \leq 6$

Since $f(y) = e^y + \frac{1}{4} e^{-y}$, we have $f'(y) = e^y -\frac{1}{4} e^{-y}$

$$L = \int_{0}^{6} \sqrt{1+ \left(e^y -\frac{1}{4} e^{-y}\right)^2}dy =  \int_{0}^{6} \sqrt{1 + \left( e^{2y} + \frac{1}{16} e^{-2y} -\frac{1}{2}\right)}dy=\int_{0}^{6} \sqrt{\frac{16e^{4y} +8e^{2y} + 1}{16 e^{2y}}} dy$$

$$= \int_{0}^{6}\sqrt {\frac{(4e^{2y}+1)^{2}}{16e^{2y}}} dy = \int_{0}^{6} \frac{4e^{2y}+1}{4e^{y}}dy = \int_{0}^{6} e^{y} + \frac{1}{4} e^{-y} dy = \left[ e^{y} -\frac{1}{4} e^{-y}\right]_{0}^{6} = e^{6} - \frac{1}{4e^{6}} - \frac{3}{4}$$


## Surface area of the curve when rotated about the axis.

The surface area of the curve when rotated about the x-axis can be found with the following formula: $$S=2\pi \int_{a}^{b} f(x) \sqrt{(f'(x))^2+1} dx$$


### Practice Exercise 3.1

Find the exact area of the surface obtained by rotating the curve about the x-axis.

$$y=x^3 , \hspace{.5cm} 0 \leq x \leq 3$$
$$f(x) = x^3$$

$$f'(x) = 3x^2$$


$$S = 2\pi\int_{0}^{3} x^3 \sqrt{1+[3x^2]^2}dx= 2\pi\int_{0}^{3}  x^3 \sqrt{1+9x^4} dx$$
Let $u=1+9x^4$ so $du=36x^3 dx$

$$=\frac{2\pi}{36} \int_{1}^{730}  {u}^{1/2} du = \frac{\pi}{18} \left[\frac{2}{3} u^{3/2}\right]_{1}^{730} = \frac{\pi}{27} \left[ u^{3/2}\right]_{1}^{730} = \frac{\pi}{27} \left(730\sqrt{730}-1  \right)$$

### Practice Exercise 3.2

Find the exact area of the surface obtained by rotating the curve about the x-axis.

$$y = \sqrt{6-x}, \hspace{.5cm} 4 \leq x \leq 6$$

$$f(x) = \left( 6-x\right)^{1/2}$$
$$f'(x) = -\frac{1}{2}\left( 6-x\right)^{-1/2}$$
$$S=2\pi \int_{4}^{6} \sqrt{6-x} \sqrt{\left( -\frac{1}{2(6-x)^{1/2}} \right)^2+1} dx =2\pi \int_{4}^{6} \sqrt{6-x} \sqrt{\left( \frac{1}{4(6-x)} \right)+1} dx$$
$$=2\pi \int_{4}^{6} \sqrt{6-x} \sqrt{\left( \frac{1+24-4x}{4(6-x)} \right)} dx=2\pi \int_{4}^{6} \sqrt{\frac{25-4x}{4}}dx =\pi \int_{4}^{6} ({25-4x})^{1/2}dx$$
let $u=25-4x$ and $du=-4dx$

$$=-\frac{\pi}{4} \int_{9}^{1} (u)^{1/2}du=\frac{2\pi}{4*3}  \left[u^{3/2} \right]_{1}^{9} = \frac{\pi}{6}[27-1] = \frac{13\pi}{3}$$

### Practice Exercise 3.3

Find the exact area of the surface obtained by rotating the curve about the x-axis.

$$y^2 = x+1, \hspace{.5cm} 0 \leq x \leq 8$$


$$f(x) = \sqrt{x+1}$$

$$f'(x) = \frac{1}{2} (x+1)^{-1/2}$$
$$S=2\pi \int_{0}^{8}  \sqrt{x+1} \sqrt{ \left( \frac{1}{2} (x+1)^{-1/2}\right)^2+1} dx=2\pi \int_{0}^{8}  \sqrt{x+1} \sqrt{ \left( \frac{1}{4 (x+1)}\right)+1} dx$$
$$=2\pi \int_{0}^{8}  \sqrt{x+1} \sqrt{\frac{4x+5}{4x+4} } =\frac{2\pi}{2} \int_{0}^{8} (4x+5)^{1/2}dx$$
Let $u=4x+5$ and $du=4dx$

$$=\frac{\pi}{4} \int_{5}^{37} u^{1/2}dx=\frac{\pi}{4}  \left[\frac{2}{3}u^{3/2} \right]_{5}^{37} =\frac{\pi}{6} \left[ 37\sqrt{37} - 5 \sqrt{5}\right]$$





